"""My migration

Revision ID: 367b3230adb2
Revises: edb1e521235b
Create Date: 2024-09-09 18:52:18.782202+10:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367b3230adb2'
down_revision = 'edb1e521235b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
