"""Initial migration	

Revision ID: 64c709f423bf	
Revises: 	
Create Date: 2024-09-13 22:05:22.076635+10:00	

"""	
from alembic import op	
import sqlalchemy as sa	
	

# revision identifiers, used by Alembic.	
revision = '64c709f423bf'	
down_revision = None	
branch_labels = None	
depends_on = None	


def upgrade():	
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_creation', sa.String(), nullable=False),
    sa.Column('markdown', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_date_creation'), 'article', ['date_creation'], unique=True)
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###	


def downgrade():	
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_article_id'), table_name='article')
    op.drop_index(op.f('ix_article_date_creation'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###