"""update article models	

Revision ID: ad653b804d00	
Revises: 69219ec6883b	
Create Date: 2024-09-16 01:00:15.086369+10:00	

"""	
from alembic import op	
import sqlalchemy as sa	
	

# revision identifiers, used by Alembic.	
revision = 'ad653b804d00'	
down_revision = '69219ec6883b'	
branch_labels = None	
depends_on = None	


def upgrade():	
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###	


def downgrade():	
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###