"""My migration

Revision ID: edb1e521235b
Revises: cb6b0e971898
Create Date: 2024-09-09 18:40:15.962706+10:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb1e521235b'
down_revision = 'cb6b0e971898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_creation', sa.String(), nullable=False),
    sa.Column('markdown', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_date_creation'), 'article', ['date_creation'], unique=True)
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_id'), table_name='article')
    op.drop_index(op.f('ix_article_date_creation'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
